global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "pos_producer"
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "pos_consumer"
    static_configs:
      - targets: ["host.docker.internal:8081"]
